In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("Loan Approval Prediction.csv")

# See columns
print(df.columns)

# Preview
df.head()

Index(['person_age', 'person_income', 'person_emp_exp', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'person_gender_male', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'previous_loan_defaults_on_file_Yes', 'loan_status'],
      dtype='object')

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
0,22.0,71948.0,0,35000.0,16.02,0.49,3.0,561,0,0,...,0,0,1,0,0,0,1,0,0,1
1,21.0,12282.0,0,1000.0,11.14,0.08,2.0,504,0,0,...,0,1,0,1,0,0,0,0,1,0
2,25.0,12438.0,3,5500.0,12.87,0.44,3.0,635,0,0,...,0,0,0,0,0,1,0,0,0,1
3,23.0,79753.0,0,35000.0,15.23,0.44,2.0,675,0,1,...,0,0,1,0,0,1,0,0,0,1
4,24.0,66135.0,1,35000.0,14.27,0.53,4.0,586,1,0,...,0,0,1,0,0,1,0,0,0,1

In [3]:
# Fill missing values
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

# Encode categorical columns
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.head()

/tmp/ipykernel_24275/3310721086.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
0,22.0,71948.0,0,35000.0,16.02,0.49,3.0,561,0,0,...,0,0,1,0,0,0,1,0,0,1
1,21.0,12282.0,0,1000.0,11.14,0.08,2.0,504,0,0,...,0,1,0,1,0,0,0,0,1,0
2,25.0,12438.0,3,5500.0,12.87,0.44,3.0,635,0,0,...,0,0,0,0,0,1,0,0,0,1
3,23.0,79753.0,0,35000.0,15.23,0.44,2.0,675,0,1,...,0,0,1,0,0,1,0,0,0,1
4,24.0,66135.0,1,35000.0,14.27,0.53,4.0,586,1,0,...,0,0,1,0,0,1,0,0,0,1

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# -----------------------------
# STEP 1: Set Correct Target
# -----------------------------
target_col = "loan_status"

# Features & Target
X = df.drop(target_col, axis=1)
y = df[target_col]

# -----------------------------
# STEP 2: Encode Target (IMPORTANT)
# -----------------------------
le = LabelEncoder()
y = le.fit_transform(y)

# -----------------------------
# STEP 3: Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------
# STEP 4: Scaling
# -----------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Data ready for ML ✅")

Data ready for ML ✅

In [5]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))

Random Forest Accuracy: 0.9401428571428572

In [7]:
import joblib

joblib.dump(rf, "credit_risk_model.pkl")

print("Model saved successfully ✅")

Model saved successfully ✅